language: php

php:
  - 5.5
  - 5.6
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8f00a1cc0caf85febd3b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
